@extends('frontend.layouts.master')

@section('title', 'TopShop || Register Page')

@section('main-content')
    <!-- Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="bread-inner">
                        <ul class="bread-list">
                            <li><a href="{{ route('home') }}">หน้าแรก<i class="ti-arrow-right"></i></a></li>
                            <li class="active"><a href="javascript:void(0);">นโยบาย</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Shop Login -->
    <section class="shop login section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-12">
                    <div class="">
                        <h2>Privacy Policy</h2><br>
                        <p>Last updated: April 23, 2021</p><br>
                        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
                            of Your information when You use the Service and tells You about Your privacy rights and how the
                            law protects You.</p><br>
                        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to
                            the collection and use of information in accordance with this Privacy Policy. This Privacy
                            Policy has been created with the help of the Privacy Policy Generator.</p><br>
                        <h2>Interpretation and Definitions</h2><br>
                        <h3>Interpretation</h3><br>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following
                            conditions. The following definitions shall have the same meaning regardless of whether they
                            appear in singular or in plural.</p><br>
                        <h2>Definitions</h2><br>
                        <p>For the purposes of this Privacy Policy:</p>
                        <div class="ml-4">
                            <p>
                                <li>Account means a unique account created for You to access our Service or parts of our
                                    Service.</li>

                                <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                                    refers
                                    to TopShop.</li>

                                <li>Cookies are small files that are placed on Your computer, mobile device or any other
                                    device
                                    by a website, containing the details of Your browsing history on that website among its
                                    many
                                    uses.</li>

                                <li>Country refers to: Thailand</li>

                                <li>Device means any device that can access the Service such as a computer, a cellphone or a
                                    digital tablet.</li>

                                <li>Personal Data is any information that relates to an identified or identifiable
                                    individual.
                                </li>

                                <li>Service refers to the Website.</li>

                                <li>Service Provider means any natural or legal person who processes the data on behalf of
                                    the
                                    Company. It refers to third-party companies or individuals employed by the Company to
                                    facilitate the Service, to provide the Service on behalf of the Company, to perform
                                    services
                                    related to the Service or to assist the Company in analyzing how the Service is used.
                                </li>

                                <li>Third-party Social Media Service refers to any website or any social network website
                                    through
                                    which a User can log in or create an account to use the Service.</li>

                                <li>Usage Data refers to data collected automatically, either generated by the use of the
                                    Service or from the Service infrastructure itself (for example, the duration of a page
                                    visit).</li>

                                <li>Website refers to TopShop, accessible from http://www.topshop-ecommerce.com</li>

                                <li>You means the individual accessing or using the Service, or the company, or other legal
                                    entity on behalf of which such individual is accessing or using the Service, as
                                    applicable.
                                </li>

                            </p>
                        </div><br>
                        <h2>Collecting and Using Your Personal Data</h2><br>
                        <h3>Types of Data Collected</h3><br>
                        <h4>Personal Data</h4><br>
                        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable
                            information that can be used to contact or identify You. Personally identifiable information may
                            include, but is not limited to:</p><br>
                        <div class="ml-4">
                            <p>
                                <li> Email address</li>

                                <li> First name and last name</li>

                                <li> Phone number</li>

                                <li> Address, State, Province, ZIP/Postal code, City</li>

                                <li> Usage Data</li>
                            </p>
                        </div><br>
                        <h3>Usage Data</h3><br>
                        <p>Usage Data is collected automatically when using the Service.</p><br>

                        <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP
                            address), browser type, browser version, the pages of our Service that You visit, the time and
                            date of Your visit, the time spent on those pages, unique device identifiers and other
                            diagnostic data.</p><br>

                        <p>When You access the Service by or through a mobile device, We may collect certain information
                            automatically, including, but not limited to, the type of mobile device You use, Your mobile
                            device unique ID, the IP address of Your mobile device, Your mobile operating system, the type
                            of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p><br>

                        <p>We may also collect information that Your browser sends whenever You visit our Service or when
                            You access the Service by or through a mobile device.</p><br>

                        <br>
                        <h2>Tracking Technologies and Cookies</h2><br>
                        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store
                            certain information. Tracking technologies used are beacons, tags, and scripts to collect and
                            track information and to improve and analyze Our Service. The technologies We use may include:

                        </p><br>
                        <div class="ml-4">
                            <p>
                                <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can
                                    instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.
                                    However, if You do not accept Cookies, You may not be able to use some parts of our
                                    Service. Unless you have adjusted Your browser setting so that it will refuse Cookies,
                                    our Service may use Cookies.</li>

                                <li>Flash Cookies. Certain features of our Service may use local stored objects (or Flash
                                    Cookies) to collect and store information about Your preferences or Your activity on our
                                    Service. Flash Cookies are not managed by the same browser settings as those used for
                                    Browser Cookies. For more information on how You can delete Flash Cookies, please read
                                    "Where can I change the settings for disabling, or deleting local shared objects?"

                                </li>

                                <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic
                                    files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                                    gifs) that permit the Company, for example, to count users who have visited those pages
                                    or opened an email and for other related website statistics (for example, recording the
                                    popularity of a certain section and verifying system and server integrity).</li>


                            </p>

                        </div><br>
                        <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal
                            computer or mobile device when You go offline, while Session Cookies are deleted as soon as
                            You close Your web browser. Learn more about cookies: What Are Cookies?.</p><br>
                        <p>We use both Session and Persistent Cookies for the purposes set out below:</p><br>
                        <div class="ml-4">
                            <p>
                                <li>
                                    <span class="font-weight-bold">Necessary / Essential Cookies</span> <br><br>

                                    Type: Session Cookies <br><br>

                                    Administered by: Th <br><br>

                                    Purpose: These Cookies are essential to provide You with services available through the
                                    Website and to enable You to use some of its features. They help to authenticate users
                                    and prevent fraudulent use of user accounts. Without these Cookies, the services that
                                    You have asked for cannot be provided, and We only use these Cookies to provide You with
                                    those services.

                                </li><br>

                                <li><span class="font-weight-bold">Cookies Policy / Notice Acceptance Cookies</span>
                                    <br><br>

                                    Type: Persistent Cookies <br><br>

                                    Administered by: Th <br><br>

                                    Purpose: These Cookies identify if users have accepted the use of cookies on the
                                    Website.



                                </li><br>

                                <li><span class="font-weight-bold">Functionality Cookies</span> <br><br>

                                    Type: Persistent Cookies <br><br>

                                    Administered by: Th <br><br>

                                    Purpose: These Cookies allow us to remember choices You make when You use the Website,
                                    such as remembering your login details or language preference. The purpose of these
                                    Cookies is to provide You with a more personal experience and to avoid You having to
                                    re-enter your preferences every time You use the Website.

                                </li>
                            </p>

                        </div><br>
                        <p>For more information about the cookies we use and your choices regarding cookies, please visit
                            our Cookies Policy or the Cookies section of our Privacy Policy.

                        </p><br>
                        <h3>Use of Your Personal Data</h3><br>
                        <p>The Company may use Personal Data for the following purposes:</p><br>
                        <div class="ml-4">
                            <p>
                                <li><span class="font-weight-bold">To provide and maintain our Service</span>
                                    , including to monitor the usage of our Service.
                                </li><br>
                                <li><span class="font-weight-bold">To manage Your Account: </span>
                                    to manage Your registration as a user of the Service. The Personal Data You provide can
                                    give You access to different functionalities of the Service that are available to You as
                                    a registered user.
                                </li><br>
                                <li><span class="font-weight-bold">For the performance of a contract: </span>
                                    the development, compliance and undertaking of the purchase contract for the products,
                                    items or services You have purchased or of any other contract with Us through the
                                    Service.
                                </li><br>
                                <li><span class="font-weight-bold">To contact You: To contact You by email</span>, telephone
                                    calls, SMS, or other equivalent forms of
                                    electronic communication, such as a mobile application's push notifications regarding
                                    updates or informative communications related to the functionalities, products or
                                    contracted
                                    services, including the security updates, when necessary or reasonable for their
                                    implementation.</li><br>


                                <li><span class="font-weight-bold">To provide You with news</span>, special offers and
                                    general information about other goods, services
                                    and events which we offer that are similar to those that you have already purchased or
                                    enquired about unless You have opted not to receive such information.</li><br>


                                <li><span class="font-weight-bold">To manage Your requests:</span> To attend and manage Your
                                    requests to Us.</li><br>


                                <li><span class="font-weight-bold">For business transfers:</span> We may use Your
                                    information to evaluate or conduct a merger,
                                    divestiture, restructuring, reorganization, dissolution, or other sale or transfer of
                                    some
                                    or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation,
                                    or
                                    similar proceeding, in which Personal Data held by Us about our Service users is among
                                    the
                                    assets transferred.</li><br>


                                <li><span class="font-weight-bold">For other purposes:</span> We may use Your information
                                    for other purposes, such as data analysis,
                                    identifying usage trends, determining the effectiveness of our promotional campaigns and
                                    to
                                    evaluate and improve our Service, products, services, marketing and your experience.
                                </li><br>

                            </p>


                        </div><br>
                        <p>We may share Your personal information in the following situations:</p><br>
                        <div class="ml-4">
                            <p>
                                <li><span class="font-weight-bold">With Service Providers: </span>
                                    We may share Your personal information with Service Providers to monitor and analyze the
                                    use of our Service, to contact You.

                                </li><br>
                                <li><span class="font-weight-bold">For business transfers: </span>
                                    We may share or transfer Your personal information in connection with, or during
                                    negotiations of, any merger, sale of Company assets, financing, or acquisition of all or
                                    a portion of Our business to another company.
                                </li><br>
                                <li><span class="font-weight-bold">With Affiliates: </span>
                                    We may share Your information with Our affiliates, in which case we will require those
                                    affiliates to honor this Privacy Policy. Affiliates include Our parent company and any
                                    other subsidiaries, joint venture partners or other companies that We control or that
                                    are under common control with Th.

                                </li><br>
                                <li><span class="font-weight-bold">With business partners:</span>We may share Your
                                    information with Our business partners to offer You certain products, services or
                                    promotions.</li><br>


                                <li><span class="font-weight-bold">With other users:</span>when You share personal
                                    information or otherwise interact in the public areas with other users, such information
                                    may be viewed by all users and may be publicly distributed outside. If You interact with
                                    other users or register through a Third-Party Social Media Service, Your contacts on the
                                    Third-Party Social Media Service may see Your name, profile, pictures and description of
                                    Your activity. Similarly, other users will be able to view descriptions of Your
                                    activity, communicate with You and view Your profile.</li><br>


                                <li><span class="font-weight-bold">With Your consent: </span>We may disclose Your personal
                                    information for any other purpose with Your consent.
                                </li><br>




                            </p>


                        </div><br>
                        <h3>Retention of Your Personal Data
                        </h3><br>
                        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set
                            out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to
                            comply with our legal obligations (for example, if we are required to retain your data to comply
                            with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p><br>
                        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally
                            retained for a shorter period of time, except when this data is used to strengthen the security
                            or to improve the functionality of Our Service, or We are legally obligated to retain this data
                            for longer time periods.</p><br>
                        <h3>Transfer of Your Personal Data</h3><br>
                        <p>Your information, including Personal Data, is processed at the Company's operating offices and in
                            any other places where the parties involved in the processing are located. It means that this
                            information may be transferred to — and maintained on — computers located outside of Your state,
                            province, country or other governmental jurisdiction where the data protection laws may differ
                            than those from Your jurisdiction.</p><br>
                        <p>Your consent to this Privacy Policy followed by Your submission of such information represents
                            Your agreement to that transfer.</p><br>
                        <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely
                            and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place
                            to an organization or a country unless there are adequate controls in place including the
                            security of Your data and other personal information.</p><br>
                        <h3>Contact Us</h3><br>
                        <p>If you have any questions about this Privacy Policy, You can contact us:</p><br>
                        <div class="ml-4">
                            <p>
                                <li>By email: topshop@gmail.com</li>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/ End Login -->
@endsection

@push('styles')
    <style>
        .shop.login .form .btn {
            margin-right: 0;
        }

        .btn-facebook {
            background: #39579A;
        }

        .btn-facebook:hover {
            background: #073088 !important;
        }

        .btn-github {
            background: #444444;
            color: white;
        }

        .btn-github:hover {
            background: black !important;
        }

        .btn-google {
            background: #ea4335;
            color: white;
        }

        .btn-google:hover {
            background: rgb(243, 26, 26) !important;
        }

    </style>
@endpush
